name: workflow

on: [push]

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: ubermag-environment
        environment-file: binder/environment.yml
        python-version: ${{ matrix.python-version }}

    - name: Install testing packages
      shell: bash -l {0}
      run: python -m pip install --upgrade pip nbval
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

    - name: Jupyter notebook tests
      shell: bash -l {0}
      run: python -m pytest -v --nbval-lax notebooks/*.ipynb
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
