name: workflow

on: [push]

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]#, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: ubermag-environment
        environment-file: binder/environment.yml
        python-version: ${{ matrix.python-version }}

    - name: Activate environment
      run: conda activate ubermag-environment

    - name: Debug
      shell: bash -l {0}
      run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

    - name: Install testing packages
      shell: bash -l {0}
      run: python -m pip install --upgrade pip nbval

    - name: Jupyter notebook tests
      shell: bash -l {0}
      run: python -m pytest -v --nbval notebooks/*.ipynb
