name: workflow

on: [push]

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: ubermag-environment
        environment-file: binder/environment.yml
        python-version: 3.8
        channel-priority: strict
        channels: conda-forge
        auto-activate-base: false

    - name: Install dependencies
      run: python -m pip install --upgrade pip nbval

    - name: Jupyter notebook tests
      run: python -m pytest -v --nbval notebooks/*.ipynb
